#!/bin/sh
set -ue
# usage: cmake-x86_64.sh output sysroot triplet

cat > "$1" << EOF
set(CMAKE_SYSTEM_NAME Hydrogen)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_SYSROOT "$2")

set(CMAKE_C_COMPILER "$3-gcc")
set(CMAKE_ASM_COMPILER "$3-gcc")
set(CMAKE_CXX_COMPILER "$3-g++")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF
