#ifndef HYDROGEN_ERROR_H
#define HYDROGEN_ERROR_H

#define ERR_INVALID_ARGUMENT 1
#define ERR_OUT_OF_MEMORY 2
#define ERR_BUSY 3
#define ERR_NOT_FOUND 4
#define ERR_NOT_A_DIRECTORY 5
#define ERR_ACCESS_DENIED 6
#define ERR_NAME_TOO_LONG 7
#define ERR_TOO_MANY_SYMLINKS 8
#define ERR_ALREADY_EXISTS 9
#define ERR_IS_A_DIRECTORY 10
#define ERR_NOT_IMPLEMENTED 11
#define ERR_DISK_FULL 12
#define ERR_OVERFLOW 13
#define ERR_INVALID_IMAGE 14

#endif // HYDROGEN_ERROR_H
