name: Create release ISO

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        arch: [x86_64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y xorriso ninja-build meson llvm-18-tools

    - name: Configure Meson
      run: |
        meson setup ${{github.workspace}}/builddir ${{github.workspace}} \
          --cross-file ${{github.workspace}}/scripts/cross/${{matrix.arch}}.txt -Dbuildtype=release -Db_lto=true \
          -Db_lto_mode=thin -Db_ndebug=true

    - name: Build
      run: meson compile -C ${{github.workspace}}/builddir

    - name: Create ISO
      run: ${{github.workspace}}/scripts/mkiso.sh proxima.iso
      working-directory: ${{github.workspace}}/builddir

    - uses: actions/upload-artifact@v4
      with:
        name: iso-image
        path: ${{github.workspace}}/builddir/proxima.iso
