name: Create release ISO

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        arch: [x86_64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y xorriso ninja-build meson bison flex libgmp3-dev libmpc-dev libmpfr-dev libisl-dev

    - name: Build
      run: ./build.py --target ${{matrix.arch}} iso

    - uses: actions/upload-artifact@v4
      with:
        name: iso-image
        path: ${{github.workspace}}/build/${{matrix.arch}}/proxima.iso
